### ISSUE TITLE
Implement Scenario

### ISSUE THREAD

**Issue by AugustT** [AugustT/CEHCraft#19]
We need to implement the scenarios that ASSIST is producing. Remember, these need only be illustrative, they do not need to be accurate.

I suggest we create a function which takes in a matrix (think raster) of land cover, and returns the same after applying the transformations the the scenario. We can then add parameters to this function to allow us to control the extent of conversions and perhaps the type of scenario run.

John has provided these transitions as a starting point

**RULES FOR MINECRAFT VERSIONS OF ASSET SCENARIOS**
 
In all cases, prioritise conversion close to existing areas of the target habitat

I’ve added woodland to the last scenario as this’ll be visually obvious in your Minecraft world.

In my scenarios, conversion to agricultural use preferentially takes place on the land most suitable for it (fertile, workable soils, flat ground etc.) and vice versa.  I assume this is a step too far for your examples, but let me know if you want to try it and I can send you the data.

**Rules for 30% agricultural expansion, intensive cropping**

Agricultural land must expand by a total of 30%. 

At least 20% expansion of arable

At least 10% expansion of improved grassland

Relative priorities (in descending order)
Improved grassland -> arable
Semi-natural grassland -> improved grassland
Semi-natural grassland -> arable
Heathland -> improved grassland

Crops (i.e. arable land) should become (at the expense of all other crops) at least:
55% winter wheat,
30% oilseed rape

**Rules for 30% semi-natural habitat expansion, diverse cropping**

Grassland and semi-natural habitats must expand by a total of 30%. 

At least 20% expansion of semi-natural grassland

At least 10% expansion of improved grassland

At least 5% expansion of broadleaf woodland

Relative priorities (in descending order)
Improved grassland -> Semi-natural grassland
Arable -> Improved grassland
Arable -> Semi-natural grassland
Improved grassland -> broadleaf woodland
Arable -> broadleaf woodland

Crops (i.e. arable land) should be at least:
20% winter wheat
10% oilseed rape
20% barley
5% field bean
5% potato
5% sugar beet
5% maize
```

**Comment by RetoSchmucki** [comment]
Sure, these scenarios might be sensible, although we don't know what is the rational behind them (if their is any). The difficulty will be to allocated changes with respect to space and spatial configuration of fields and land boundaries. Remember that a raster has no defined boundaries. One option would be to use the field boundaries (vector format) to identify coherent patch transition. Or some rules enabling spatial contagion of changes with minimum contiguous areas, so you avoid ending a block of forest in the middle of a oil seed rape field, or the reverse :smile:

**Comment by AugustT** [comment]
Yeah, I have the feeling this is not going to be straight forward!
