### ISSUE TITLE
Add variation to hill landscape flowers

### ISSUE THREAD

**Issue by AugustT** [AugustT/CEHCraft#4]
I'm not sure what the habitat is but in the lake district the hills are covered with purple tulips in every square. Let's add some variation to this to make it more interesting.

**Comment by GPowney** [comment]
This was the heather grassland land cover category, I've added variation to the flower selection for the various heather categories.  I'll go through and check for other "boring" categories and add some excitement!

**Comment by AugustT** [comment]
Good stuff. I think the woodland and grassland are the boring ones that need a little grass and a few flowers.
