### ISSUE TITLE
Add river overlay

### ISSUE THREAD

**Issue by AugustT** [AugustT/CEHCraft#6]
Using a vector map of rivers we should be able to better represent them in out maps

**Comment by RetoSchmucki** [comment]
here is the script and layer for the rivers

uk_rivers <- sf::st_read('W:/PYWELL_SHARED/Pywell Projects/BRC/Tom August/Minecraft/base_layers/uk_rivers/uk_rivers.shp')

## subset
uk_rivers2 <- uk_rivers[uk_rivers$STRAHLE > 1,]
plot(uk_rivers2[,"geometry"])

**Comment by RetoSchmucki** [comment]
do the same for canals
uk_canals <- sf::st_read('W:/PYWELL_SHARED/Pywell Projects/BRC/Tom August/Minecraft/base_layers/uk_rivers/uk_canals.shp')

**Comment by AugustT** [comment]
your my hero

**Comment by AugustT** [comment]
I'll close this once I have coded it it

**Comment by AugustT** [comment]
Now coded, thanks @RetoSchmucki
