### ISSUE TITLE
Add road overlay

### ISSUE THREAD

**Issue by AugustT** [AugustT/CEHCraft#7]
We should be able to add major roads to the map which will help people to recognise locations. I suggest we buffer rods so that they are 2 blocks wide at a minimum. @GPowney perhaps there are different block types we could use for motorways vs A roads? Equally the motorways could be buffered to be larger then the A roads.

**Comment by RetoSchmucki** [comment]
@AugustT and @GPowney 
Just added the scripts and layers to build and merge the road layer to the land cover. 
script is found in misc folder, build_uk_road... and crop_uk_road...

**Comment by AugustT** [comment]
Thank @RetoSchmucki that looks great, I will have a play and let you know if I have any questions
